### ISSUE TITLE
训练的过程中为何出现这么多得警告

### ISSUE THREAD

**Issue by QIANXUNZDL123** [tinyvision/DAMO-YOLO#43]
### Before Asking

- [X] I have read the [README](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for finetune on your data](https://github.com/tinyvision/DAMO-YOLO/blob/master/README.md#Finetune%20on%20your%20data) carefully and organize my dataset correctly; 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the DAMO-YOLO [issues](https://github.com/tinyvision/DAMO-YOLO/issues) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/46549527/207251377-bd58be60-b1c6-41fc-b8d9-6cf6a57a20ce.png)
为什么会出现这么警告。。。

**Comment by QIANXUNZDL123** [comment]
![image](https://user-images.githubusercontent.com/46549527/207310249-b6756fc5-28ed-4bb4-b43a-cb224c0e7d55.png)
还有为啥跑着跑着出现这个错误！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by cwhgn** [comment]
For the first question, it caused by the wrong pytorch version. We recommend you to use pytorch==1.7.0 as listed in our tutorial.

For the second question, it is due to the communication timeout among your multiple GPUs. One possible solution is to replace L48 in tools/train.py https://github.com/tinyvision/DAMO-YOLO/blob/6e38813220900955d0f6138429c91a33a79c922f/tools/train.py#L48
with
```
torch.distributed.init_process_group(backend='nccl', init_method='env://', timeout=datetime.timedelta(seconds=5400))
